"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-12 21:09:29.157300

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import paro.db.types

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "downtime_reason",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("default_is_planned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["downtime_reason.id"],
            name=op.f("fk_downtime_reason_parent_id_downtime_reason"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downtime_reason")),
        sa.UniqueConstraint("code", name=op.f("uq_downtime_reason_code")),
    )
    op.create_table(
        "production_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_line")),
        sa.UniqueConstraint("code", name=op.f("uq_production_line_code")),
    )
    op.create_table(
        "machine",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"], ["production_line.id"], name=op.f("fk_machine_line_id_production_line")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine")),
        sa.UniqueConstraint("line_id", "code", name=op.f("uq_machine_line_id")),
    )
    op.create_table(
        "production_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("interval_start", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("interval_end", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("good_count", sa.Integer(), nullable=False),
        sa.Column("ideal_cycle_time_seconds", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "good_count >= 0 AND good_count <= total_count",
            name=op.f("ck_production_record_valid_counts"),
        ),
        sa.CheckConstraint(
            "interval_end > interval_start", name=op.f("ck_production_record_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["production_line.id"],
            name=op.f("fk_production_record_line_id_production_line"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_record")),
        sa.UniqueConstraint("source", "external_id", name=op.f("uq_production_record_source")),
    )
    with op.batch_alter_table("production_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_production_record_line_id_interval_start",
            ["line_id", "interval_start"],
            unique=False,
        )

    op.create_table(
        "shift",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column("planned_start_utc", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("planned_end_utc", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("planned_break_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"], ["production_line.id"], name=op.f("fk_shift_line_id_production_line")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shift")),
    )
    op.create_table(
        "downtime_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=True),
        sa.Column("started_at", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("ended_at", paro.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("reason_id", sa.Integer(), nullable=False),
        sa.Column("is_planned", sa.Boolean(), nullable=False),
        sa.Column("operator_note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", paro.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at", name=op.f("ck_downtime_event_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["production_line.id"],
            name=op.f("fk_downtime_event_line_id_production_line"),
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machine.id"], name=op.f("fk_downtime_event_machine_id_machine")
        ),
        sa.ForeignKeyConstraint(
            ["reason_id"],
            ["downtime_reason.id"],
            name=op.f("fk_downtime_event_reason_id_downtime_reason"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downtime_event")),
        sa.UniqueConstraint("source", "external_id", name=op.f("uq_downtime_event_source")),
    )
    with op.batch_alter_table("downtime_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_downtime_event_line_id_started_at", ["line_id", "started_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("downtime_event", schema=None) as batch_op:
        batch_op.drop_index("ix_downtime_event_line_id_started_at")

    op.drop_table("downtime_event")
    op.drop_table("shift")
    with op.batch_alter_table("production_record", schema=None) as batch_op:
        batch_op.drop_index("ix_production_record_line_id_interval_start")

    op.drop_table("production_record")
    op.drop_table("machine")
    op.drop_table("production_line")
    op.drop_table("downtime_reason")
    # ### end Alembic commands ###
